### PR TITLE
Add back to home

### PR DESCRIPTION
**Pull request by mjvbz**
I added a link on 404 page which redirects user to the home page of the website which may help people to back to home and explore the website! 

I think it may help the team! Thank you

### CODE REVIEW

**Review by ejcheng — APPROVED** [review]
LGTM 👍

**Review by Shon-TG — APPROVED** [review]
Looks good for me 👍

**Comment by mjvbz** [comment]
Is this project still active @github

**Review by miraclecra — APPROVED** [review]

**Review by anomal — APPROVED** [review]

**Comment by mjvbz** [comment]
Thanks for merging!

**Comment by mjvbz** [comment]
@all-contributors add @mjvbz to contributors

**Comment by mjvbz** [comment]
@all-contributors Please add @mjvbz for code

**Review by Nickochoa32 — APPROVED** [review]

**Pull request merged**
