### PR TITLE
covid19: Compare Country Trajectories

### PR DESCRIPTION
**Pull request by pratapvardhan**
You should be able to see the [interactive plots here](https://nbviewer.jupyter.org/github/pratapvardhan/notebooks/blob/0fee9fb1b7e5b57a926427e7d88104b80b692d67/covid19/covid19-compare-country-trajectories.ipynb). Basic idea here is to compare growth trajectories with Italy, South Korea & Japan. User can use (click, shift+click) legend to add countries. And last chart provides a country dropdown for a focused view. Hopefully, these representations reduces clutter.

Let me know, if you find this a useful addition and anything else you'd like to see added?

### CODE REVIEW

**Comment by hamelsmu** [comment]
Excellent!  Can you add a 33% Daily Growth Line similar to https://covid19dashboards.com/growth-bayes/ ?

**Comment by pratapvardhan** [comment]
@hamelsmu -- Good point! [Added 33% reference line](https://nbviewer.jupyter.org/github/pratapvardhan/notebooks/blob/97cfa7750e673ead24c0efb06604ce5dc4863a24/covid19/covid19-compare-country-trajectories.ipynb) to the plots.

**Comment by hamelsmu** [comment]
This is excellent work.  @jph00 You should see this work by @pratapvardhan  it is the same COVID-19 chart you see on the Financial Times, but interactive, updated hourly and also with multiple views.  

@pratapvardhan I'm really impressed by this.  Also I would categorize this PR as "beautiful" and very well put together, you really paid attention to detail.

**Comment by hamelsmu** [comment]
@pratapvardhan for some reason the charts are not rendering on GitHub pages, even though they are rendering locally.  Really baffling.  I have temporarily marked this as hidden until I can figure it out.  You can see this at https://covid19dashboards.com/compare-country-trajectories/

**Comment by hamelsmu** [comment]
@pratapvardhan fixed it

**Comment by pratapvardhan** [comment]
Thanks @hamelsmu !

**Comment by hamelsmu** [comment]
Hi @pratapvardhan would you be willing to do the same set of charts for the Death Rate? 

Like this https://twitter.com/jburnmurdoch/status/1239998499758002182?s=21

Awesome work

**Comment by pratapvardhan** [comment]
@hamelsmu -- let me send a PR in sometime.

**Pull request merged**
