### PR TITLE
Add interactive growth chart for US

### PR DESCRIPTION
**Pull request by aimran-adroll**
Add interactive confirmed case (daily+cuml) chart with map for US states

### CODE REVIEW

**Comment by hamelsmu** [comment]
@aimran-adroll nice work!  Looks good except I dont' see `us-growth-state-map.png` being created by your notebook anywhere?

**Comment by hamelsmu** [comment]
Hi @aiman-adroll I believe your chart isn’t updating with numbers, anymore.  I’ll go ahead and hide this from view until it’s fixed

**Comment by aimran-adroll** [comment]
@hamelsmu Thanks for flagging it. 

May I ask how did you conclude its no longer updating?

I quickly checked the JHU github source for CA -- its showing 952 active cases for the 3/19 (latest date on file). This lines up with whats shown on the map/chart

https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv

**Comment by hamelsmu** [comment]
@aimran-adroll This is my mistake - when hovering over the state of Oregon for example, if you don't put your mouse close enought to the circle it will show zero cases.  ( Is there a way to fix this?)

The dashboard never got unhidden :)

**Comment by hamelsmu** [comment]
Here is a screenshot

image

**Pull request merged**
